import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import React from 'react'
import axios from 'axios'
import Header from 'components/Header/Header'
import Dashboard from 'components/Dashboard/Dashboard'
import styles from 'styles/Home.module.scss'
import AudioPlayer from 'components/AudioPlayer/AudioPlayer'
import AlbumGrid from 'components/Album/AlbumGrid'

const Home: NextPage = () => {

    const [albums, setAlbums] = React.useState([])
    const [nowPlaying, setNowPlaying] = React.useState([])

    console.log('now: ', nowPlaying)

    React.useEffect(() => {
        (async () => {
              
            const response = await axios({
                method: 'get',
                url: 'http://192.168.1.21:4000/album?page=1&limit=100',
                withCredentials: true
            })
            setAlbums(response.data.results)
        })()
    }, [])

    return (
        <div className={styles.home}>
            <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <Dashboard albums={albums} >
                <AlbumGrid albums={albums} setNowPlaying={setNowPlaying} />
            </Dashboard>
            {
                nowPlaying.length && (
                    <AudioPlayer nowPlaying={nowPlaying} />
                )
            }
        </div>
    )
}



export const getServerSideProps: GetServerSideProps = async (context) => {
    
    const authCookie = context.req.cookies['user']
    const isLoggedIn = authCookie ? true : false

    if (!isLoggedIn) {
        return {
            redirect: {
                destination: '/login',
                permanent: false
            }
        }
    }

    return { props: {}}
}

export default Home
