import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react'


const Home: NextPage = () => {

    return (
        <div className={styles.container}>
            <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                Hello World
            </div>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
    
    const authCookie = context.req.cookies['user']
    const isLoggedIn = authCookie ? true : false

    if (!isLoggedIn) {
        return {
            redirect: {
                destination: '/login',
                permanent: false
            }
        }
    }

    return { props: {}}
}

export default Home
